version: '3.5'
services: 
    api-service:
        build: ./api/
        volumes: 
            - ./api/:/usr/src/docker/
        ports: 
            - 5000:5000
        environment: 
            PORT: 5000
            FLASK_DEBUG: 1
